/**
* CryptoSky
* This is an API description for COINCAP API 2.0
*
* OpenAPI spec version: 1.0.0
* Contact: mrdeakd@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import deak.david.mszr.cryptosky.disk.model.DBCoin


/**
 * 
 * @param id 
 * @param rank 
 * @param symbol 
 * @param name 
 * @param supply 
 * @param maxSupply 
 * @param marketCapUsd 
 * @param volumeUsd24Hr 
 * @param priceUsd 
 * @param changePercent24Hr 
 * @param vwap24Hr 
 */
data class Coin (
    val id: String?,
    val rank: String?,
    val symbol: String?,
    val name: String?,
    val supply: String?,
    val maxSupply: String?,
    val marketCapUsd: String?,
    val volumeUsd24Hr: String?,
    val priceUsd: String?,
    val changePercent24Hr: String?,
    val vwap24Hr: String?
)

fun Coin.mapToDomainDBCoin(): DBCoin =
    DBCoin(
        id = this.id ?: "",
        rank = this.rank ?: "",
        symbol = this.symbol ?: "",
        name = this.name ?: "",
        supply = this.supply ?: "",
        maxSupply = this.maxSupply ?: "",
        marketCapUsd = this.marketCapUsd ?: "",
        volumeUsd24Hr = this.volumeUsd24Hr ?: "",
        priceUsd = this.priceUsd ?: "",
        changePercent24Hr = this.changePercent24Hr ?: "",
        vwap24Hr = this.vwap24Hr ?: ""
    )

