/**
* CryptoSky
* This is an API description for COINCAP API 2.0
*
* OpenAPI spec version: 1.0.0
* Contact: mrdeakd@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Coin

/**
 * 
 * @param &#x60;data&#x60; 
 * @param timestamp 
 */
data class ResponseObjectOfCoin (
    val `data`: Coin? = null,
    val timestamp: kotlin.Long? = null
) {

}

