/**
* CryptoSky
* This is an API description for COINCAP API 2.0
*
* The version of the OpenAPI document: 1.0.0
* Contact: mrdeakd@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package deak.david.mszr.cryptosky.data.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import deak.david.mszr.cryptosky.disk.model.DBCoin

/**
 * 
 * @param id 
 * @param rank 
 * @param symbol 
 * @param name 
 * @param supply 
 * @param maxSupply 
 * @param marketCapUsd 
 * @param volumeUsd24Hr 
 * @param priceUsd 
 * @param changePercent24Hr 
 * @param vwap24Hr 
 */
@JsonClass(generateAdapter = true)
data class Coin (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "rank")
    val rank: kotlin.String? = null,
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "supply")
    val supply: kotlin.String? = null,
    @Json(name = "maxSupply")
    val maxSupply: kotlin.String? = null,
    @Json(name = "marketCapUsd")
    val marketCapUsd: kotlin.String? = null,
    @Json(name = "volumeUsd24Hr")
    val volumeUsd24Hr: kotlin.String? = null,
    @Json(name = "priceUsd")
    val priceUsd: kotlin.String? = null,
    @Json(name = "changePercent24Hr")
    val changePercent24Hr: kotlin.String? = null,
    @Json(name = "vwap24Hr")
    val vwap24Hr: kotlin.String? = null
)

fun Coin.mapToDomainDBCoin(): DBCoin =
    DBCoin(
        id = this.id ?: "",
        rank = this.rank ?: "",
        symbol = this.symbol ?: "",
        name = this.name ?: "",
        supply = this.supply ?: "",
        maxSupply = this.maxSupply ?: "",
        marketCapUsd = this.marketCapUsd ?: "",
        volumeUsd24Hr = this.volumeUsd24Hr ?: "",
        priceUsd = this.priceUsd ?: "",
        changePercent24Hr = this.changePercent24Hr ?: "",
        vwap24Hr = this.vwap24Hr ?: ""
    )

