/**
* CryptoSky
* This is an API description for COINCAP API 2.0
*
* The version of the OpenAPI document: 1.0.0
* Contact: mrdeakd@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package deak.david.mszr.cryptosky.data.network.model

import deak.david.mszr.cryptosky.data.network.model.Coin

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param data 
 * @param timestamp 
 */
@JsonClass(generateAdapter = true)
data class ResponseObjectOfCoin (
    @Json(name = "data")
    val data: Coin? = null,
    @Json(name = "timestamp")
    val timestamp: kotlin.Long? = null
)

